use_frameworks!

platform :ios, '10.0'

target 'UICollectionViewWaterFallFlowLayout_Example' do
  pod 'UICollectionViewWaterFallFlowLayout', :path => '../'

  target 'UICollectionViewWaterFallFlowLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
